<a href="https://colab.research.google.com/github/np03cs4s240161-dot/Concept-technology-of-AI/blob/main/worksheet1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#To-Do-Task
#4.1 Warming Up Exercise
import numpy as np

#----------------------------------------------------
# Task 1: Create an empty (zero-filled) 2x2 array
#----------------------------------------------------
print("\nTask 1 Answers:")
matrix = np.zeros((2, 2))
print(matrix)

#----------------------------------------------------
# Task 2: Create an all-ones array of size 4x2
#----------------------------------------------------
print("\nTask 2 Answers:")
matrix = np.ones((4, 2))
print(matrix)

#----------------------------------------------------
# Task 3: Create an array filled with a specific value
#----------------------------------------------------
print("\nTask 3 Answers:")
arr = np.full((2, 2), 5)
print(arr)

#----------------------------------------------------
# Task 4: Create a zeros array with the same shape as another array
#----------------------------------------------------
print("\nTask 4 Answers:")
a = np.array([[1, 2],
              [3, 4]])
b = np.zeros_like(a)
print(b)

#----------------------------------------------------
# Task 5: Create a ones array with the same shape as another array
#----------------------------------------------------
print("\nTask 5 Answers:")
a = np.array([[1, 2],
              [3, 4]])
b = np.ones_like(a)
print(b)

#----------------------------------------------------
# Task 6: Convert a Python list into a NumPy array
#----------------------------------------------------
print("\nTask 6 Answers:")
new_list = [1, 2, 3, 4]
b = np.array(new_list)
print(b)



Task 1 Answers:
[[0. 0.]
 [0. 0.]]

Task 2 Answers:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Task 3 Answers:
[[5 5]
 [5 5]]

Task 4 Answers:
[[0 0]
 [0 0]]

Task 5 Answers:
[[1 1]
 [1 1]]

Task 6 Answers:
[1 2 3 4]


In [ ]:
#Problem-2 Array Manipulation
import numpy as np

#----------------------------------------------------
# Task 1: Create an array with values from 10 to 48
#----------------------------------------------------
print("\nTask 1 Answers:")
a = np.arange(10, 49)
print(a)

#----------------------------------------------------
# Task 2: Create a 3x3 matrix with values from 0 to 8
#----------------------------------------------------
print("\nTask 2 Answers:")
a = np.arange(9).reshape(3, 3)
print(a)

#----------------------------------------------------
# Task 3: Create a 3x3 identity matrix
#----------------------------------------------------
print("\nTask 3 Answers:")
a = np.eye(3, 3)
print(a)

#----------------------------------------------------
# Task 4: Create a random array of 30 values and print the mean
#----------------------------------------------------
print("\nTask 4 Answers:")
a = np.random.random(30)
b = np.mean(a)
print("Mean:", b)

#----------------------------------------------------
# Task 5: Create a 10x10 random matrix & print min & max values
#----------------------------------------------------
print("\nTask 5 Answers:")
a = np.random.random((10, 10))
b = a.min()
c = a.max()
print("Min value:", b)
print("Max value:", c)

#----------------------------------------------------
# Task 6: Create a vector of size 10 with zeros, except the 5th element = 1
#----------------------------------------------------
print("\nTask 6 Answers:")
a = np.zeros(10)
a[4] = 1
print(a)

#----------------------------------------------------
# Task 7: Reverse a given array
#----------------------------------------------------
print("\nTask 7 Answers:")
arr = np.array([1, 2, 0, 0, 4, 0])
b = arr[::-1]
print(b)

#----------------------------------------------------
# Task 8: Create a 5x5 matrix with 1s around the border & 0 inside
#----------------------------------------------------
print("\nTask 8 Answers:")
a = np.ones((5, 5))
a[1:-1, 1:-1] = 0
print(a)

#----------------------------------------------------
# Task 9: Create an 8x8 chessboard pattern (1s and 0s)
#----------------------------------------------------
print("\nTask 9 Answers:")
a = np.zeros((8, 8))

# Fill alternating pattern
a[1::2, ::2] = 1
a[::2, 1::2] = 1

print(a)



Task 1 Answers:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]

Task 2 Answers:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Task 3 Answers:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Task 4 Answers:
Mean: 0.6374467789720174

Task 5 Answers:
Min value: 0.006447947467576487
Max value: 0.9886056053706012

Task 6 Answers:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Task 7 Answers:
[0 4 0 0 2 1]

Task 8 Answers:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

Task 9 Answers:
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
#Problem-3 Array Operations
import numpy as np

# Given arrays and vectors
x = np.array([[1, 2],
              [3, 5]])

y = np.array([[5, 6],
              [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

#----------------------------------------------------
# Task 1: Matrix Addition (x + y)
#----------------------------------------------------
print("\nTask 1 Answers:")
add = x + y  # element-wise addition
print(add)

#----------------------------------------------------
# Task 2: Matrix Subtraction (x - y)
#----------------------------------------------------
print("\nTask 2 Answers:")
sub = x - y  # element-wise subtraction
print(sub)

#----------------------------------------------------
# Task 3: Element-wise Multiplication (x * y)
#----------------------------------------------------
print("\nTask 3 Answers:")
m = x * y  # multiplication element by element
print(m)

#----------------------------------------------------
# Task 4: Square each element of x
#----------------------------------------------------
print("\nTask 4 Answers:")
sq = x ** 2  # square of each element
print(sq)

#----------------------------------------------------
# Task 5: Dot products
#   (a) v . w
#   (b) x . v
#   (c) x . y
#----------------------------------------------------
print("\nTask 5 Answers:")

# Dot product between vectors v and w
dot = np.dot(v, w)
print("Dot product v . w =", dot)

# Dot product between matrix x and vector v
dot = np.dot(x, v)
print("Dot product x . v =", dot)

# Dot product between matrices x and y
dot = np.dot(x, y)
print("Dot product x . y =\n", dot)

#----------------------------------------------------
# Task 6: Concatenate matrices x and y vertically
#----------------------------------------------------
print("\nTask 6 Answers:")
concat = np.concatenate((x, y), axis=0)
print(concat)

#----------------------------------------------------
# Task 7: Concatenate vectors v and w
#----------------------------------------------------
print("\nTask 7 Answers:")
concat = np.concatenate((v, w))
print(concat)









Task 1 Answers:
[[ 6  8]
 [10 13]]

Task 2 Answers:
[[-4 -4]
 [-4 -3]]

Task 3 Answers:
[[ 5 12]
 [21 40]]

Task 4 Answers:
[[ 1  4]
 [ 9 25]]

Task 5 Answers:
Dot product v . w = 219
Dot product x . v = [29 77]
Dot product x . y =
 [[19 22]
 [50 58]]

Task 6 Answers:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Task 7 Answers:
[ 9 10 11 12]


In [ ]:
#Problme-4 Matrix Operations
import numpy as np

# Given matrices
A = np.array([[3, 4],
              [7, 8]])

B = np.array([[5, 3],
              [2, 1]])

# -----------------------------------------------------
# 1. PROVE A * A^-1 = I
# -----------------------------------------------------
print("\nTask 1: Prove A * A^-1 = I")

A_inv = np.linalg.inv(A)
identity = np.dot(A, A_inv)
print("A * A^-1 =\n", identity)


# -----------------------------------------------------
# 2. PROVE AB ≠ BA
# -----------------------------------------------------
print("\nTask 2: Prove AB ≠ BA")

AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB =\n", AB)
print("BA =\n", BA)
print("Is AB equal to BA? ->", np.array_equal(AB, BA))


# -----------------------------------------------------
# 3. PROVE (AB)^T = B^T A^T
# -----------------------------------------------------
print("\nTask 3: Prove (AB)^T = B^T A^T")

AB_T = np.dot(A, B).T
BT_AT = np.dot(B.T, A.T)

print("(AB)^T =\n", AB_T)
print("B^T A^T =\n", BT_AT)
print("Is (AB)^T equal to B^T A^T? ->", np.allclose(AB_T, BT_AT))


# -----------------------------------------------------
# 4. SOLVE SYSTEM OF LINEAR EQUATIONS (Inverse Method)
# -----------------------------------------------------
print("\nTask 4: Solve system using inverse")

# System of equations:
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

A_eq = np.array([[2, -3, 1],
                 [1, -1, 2],
                 [3, 1, -1]])

B_eq = np.array([-1, -3, 9])

# Solve X = A^-1 B
X = np.dot(np.linalg.inv(A_eq), B_eq)

print("Solution [x, y, z] =", X)










Task 1: Prove A * A^-1 = I
A * A^-1 =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Task 2: Prove AB ≠ BA
AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]
Is AB equal to BA? -> False

Task 3: Prove (AB)^T = B^T A^T
(AB)^T =
 [[23 51]
 [13 29]]
B^T A^T =
 [[23 51]
 [13 29]]
Is (AB)^T equal to B^T A^T? -> True

Task 4: Solve system using inverse
Solution [x, y, z] = [ 2.  1. -2.]
